webpackJsonp(["tabnav/publish/target"],{"215bf17984":function(c,d,a){c.exports=a("xqfG")},"M+XO":function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});d.SELECTORS=d.CLASSES=d.VALUES=d.EVENTS_NAMESPACE=d.MODULE_NAME=void 0;c=a("akNE");a=d.MODULE_NAME="tabnav";d.EVENTS_NAMESPACE="."+a;d.VALUES={errorNotFound:"The page could not be found"};a=d.CLASSES={accordionHead:a+"__accordionHead",accordionLink:a+"__accordionLink",base:a+"__base",content:a+"__content",link:a+"__link",navHead:a+"__head",
tabnav:a+"__tabs"};d.SELECTORS=(0,c.createSelectorsFromClasses)(a)},Tnqr:function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});d.default=function(){var a=void 0,c=void 0,e={},d=function(a){var b=$(this);a.preventDefault();b.hasClass(g.NN_CLASSES.isActive)?b.removeClass(g.NN_CLASSES.isActive).next().addClass(g.NN_CLASSES.isHidden):(e.navHead.removeClass(g.NN_CLASSES.isActive),e.navContent.addClass(g.NN_CLASSES.isHidden),b.addClass(g.NN_CLASSES.isActive).next().removeClass(g.NN_CLASSES.isHidden))},
b=function(a){var b=$(this).attr("href");e.navHead.each(function(){var e=$(this).find("a");if(b===e.attr("data-href"))return a.preventDefault(),a.stopPropagation(),e.click(),!1})},l=function(){e.el.find(a.accordionLink).each(function(){var a=$(this),b=a.attr("href");a.attr("data-href",b).attr("href","")})};return{init:function(p,f){e.el=p;a=f.SELECTORS;c=f.EVENTS_NAMESPACE;e.mobile=e.el.find(h.NN_SELECTORS.isMobile);e.navHead=e.mobile.find(a.accordionHead);e.navContent=e.mobile.find(a.content);l();
e.el.on("click"+c,a.accordionHead,d);e.el.on("click"+c,"a",b);e.mobile.find(h.NN_SELECTORS.isActive).length||e.navHead.first().addClass(h.NN_SELECTORS.isActive).next().removeClass(g.NN_CLASSES.isHidden)},destroy:function(){k.default.cleanDOMElements(e.el);e.el.off(c);(0,f.nullifyPropertiesOnObject)(e)}}};var f=a("BSTm"),k=(c=a("opt3"))&&c.__esModule?c:{default:c},h=a("bdJJ"),g=a("K6O9")},"g/ae":function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});d.default=function(){var a=void 0,c=void 0,
b={},d=function(a){a.preventDefault();b.navHead.removeClass(g.NN_CLASSES.isActive);b.navContent.addClass(g.NN_CLASSES.isHidden);$(this).addClass(g.NN_CLASSES.isActive);b.navContent.eq($(this).index()).removeClass(g.NN_CLASSES.isHidden)},p=function(a){var c=$(this).attr("href");b.navHead.each(function(){var b=$(this).find("a");if(c===b.attr("data-href"))return b.click(),a.preventDefault(),!1})},t=function(){b.el.find(a.link).each(function(){var a=$(this),b=a.attr("href");a.attr("data-href",b).attr("href",
"")})};return{init:function(e,l){b.el=e;a=l.SELECTORS;c=l.EVENTS_NAMESPACE;b.desktop=b.el.find(h.NN_SELECTORS.isDesktop);b.navHead=b.desktop.find(a.navHead);b.navContent=b.desktop.siblings(a.content);b.navigation=b.el.find(a.tabnav);t();b.el.on("click"+c,a.navHead,d);b.el.on("click"+c,"a",p);b.el.find(h.NN_SELECTORS.isActive).length||(b.navHead.first().addClass(g.NN_CLASSES.isActive),b.navContent.first().removeClass(g.NN_CLASSES.isHidden));l.debouncer=(0,m.Debouncer)({waitMax:500,debounceMs:200});
l.debouncer.debounce(function(){f.default.start(b.navigation);l.debouncer.kill()})},destroy:function(){f.default.stop(b.navigation);n.default.cleanDOMElements(b.el);b.el.off(c);(0,k.nullifyPropertiesOnObject)(b)},contextChange:function(){f.default.stop(b.navigation);f.default.start(b.navigation)}}};var f=(c=a("EeOq"))&&c.__esModule?c:{default:c},k=a("BSTm"),h=a("bdJJ"),g=a("K6O9"),m=a("zF+s"),n=(a=a("opt3"))&&a.__esModule?a:{default:a}},opt3:function(c,d,a){Object.defineProperty(d,"__esModule",{value:!0});
var f=a("M+XO"),k=a("K6O9"),h=a("bdJJ");d.default={cleanDOMElements:function(a){a.find(h.NN_SELECTORS.isActive).removeClass(k.NN_CLASSES.isActive);a.find(f.SELECTORS.content).addClass(k.NN_CLASSES.isHidden);a.find(f.SELECTORS.content).empty()}}},xqfG:function(c,d,a){function f(a){return a&&a.__esModule?a:{default:a}}c=a("2b3J");var k=f(c),h=a("+ly4"),g=a("BSTm"),m=a("M+XO"),n=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=
a[c]);b.default=a;return b}(m);c=a("e3M3");var e=f(c);c=a("g/ae");var u=f(c);a=a("Tnqr");var b=f(a);window.nn[m.MODULE_NAME]=function(){var a={},c={},d=function(){c.currentContext&&c.currentContext.destroy(a.el,c.config)},f=function(){c.currentContext.init(a.el,c.config)},q=function(){c.currentContext=new b.default},r=function(){c.currentContext=new u.default},v=function(){q()},w=function(){r()},x=function(){c.currentContext.contextChange()};return{init:function(b,g){a.el=b;c.config=$.extend(!0,{},
n,g);e.default.start(this,{onInitInMobileContext:q,onInitInDesktopContext:r,onAfterInitContext:f,onChangedToMobileContext:v,onChangedToDesktopContext:w,onBeforeChangedContext:d,onAfterChangedContext:f,onChangedOnDesktopContext:x});k.default.pub(h.NN_EVENTS_MODULE_LIFECYCLE.afterInit,{$el:b,moduleName:m.MODULE_NAME})},destroy:function(){e.default.stop(this);(0,g.nullifyPropertiesOnObject)(a)}}}}},["215bf17984"]);