/*
 Pause jQuery plugin v0.1

 Copyright 2010 by Tobia Conforto <tobia.conforto@gmail.com>

 Based on Pause-resume-animation jQuery plugin by Joe Weitzel

 This program is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 of the License, or(at your option)
 any later version.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 more details.

 You should have received a copy of the GNU General Public License along with
 this program; if not, write to the Free Software Foundation, Inc., 51
 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*/
webpackJsonp(["stagepushable/publish/target"],{"2sPK":function(f,d,b){function e(a,c,b,d){a&&a.addClass(g.CLASSES.stageContainerFadeIn);c&&c.addClass(g.CLASSES.stageFootnoteFadeIn);b&&b.addClass(g.CLASSES.stageSlickDotsFadeIn);d&&d.addClass(g.CLASSES.stageCountdownFadeIn)}function n(a,c){a.removeClass(g.CLASSES.stageContainerFadeIn);c&&c.removeClass(g.CLASSES.stageContainerFadeIn)}function k(a){var c=Date.now(),b=a.dataset.countdownTargetTime,h=b-c;if(c>=b)a.style.display="none";else{c=Math.floor(h/
w);b=Math.floor((h-w*c)/R);var d=Math.floor((h-w*c-b*R)/Y);h=Math.floor((h-w*c-b*R-d*Y)/1E3);var e=[(0,x.padLeadingZeroes)(c,2),(0,x.padLeadingZeroes)(b,2),(0,x.padLeadingZeroes)(d,2),(0,x.padLeadingZeroes)(h,2)];Array.prototype.forEach.call(a.querySelectorAll("["+g.ATTRIBUTES.dataCountdownViewListItem+"]")||[],function(a,c){a.innerHTML=e[c]})}}function p(a){var c=JSON.parse(window.sessionStorage.getItem(M.ME_SESSION_STORAGE_KEYS.wkoUserData)),b=JSON.parse(window.sessionStorage.getItem(D.CIAM_SESSION_STORAGE_KEYS.wkoUserDataExtended)),
h=window.sessionStorage.getItem(D.CIAM_SESSION_STORAGE_KEYS.firstname),d=window.sessionStorage.getItem(D.CIAM_SESSION_STORAGE_KEYS.lastname),e=void 0,f=void 0,O=void 0,p=void 0,w=void 0,r=void 0;b=b?b[g.WKO_PARAMETERS.marketSpecificSalutation]:"";c&&(e=c[g.WKO_PARAMETERS.salutation],f=c[g.WKO_PARAMETERS.title],O=c[g.WKO_PARAMETERS.lastName2],p=c[g.WKO_PARAMETERS.namePrefix],w=c[g.WKO_PARAMETERS.middleInitial],r=e?e:f);c=a.personalizedStage.element[0].querySelector(g.SELECTORS.stageHeadline);a.personalizedStage.originalPersonalizedText=
c.innerText;c.innerText=a.personalizedStage.originalPersonalizedText.replace(g.PLACEHOLDERS.firstName,h).replace(g.PLACEHOLDERS.lastName,d).replace(g.PLACEHOLDERS.salutation,e).replace(g.PLACEHOLDERS.title,f).replace(g.PLACEHOLDERS.namePrefix,p).replace(g.PLACEHOLDERS.salutationOrTitle,r).replace(g.PLACEHOLDERS.middleInitial,w).replace(g.PLACEHOLDERS.marketSpecificSalutation,b).replace(g.PLACEHOLDERS.lastName2,O)}function m(a,c){a.personalizedStage.index=c.stageItems.index(a.personalizedStage.element);
a.personalizedStage.element.detach();a.personalizedStage.isVisible=!1}function q(a,c){a.personalizedStage.isVisible||(0===a.personalizedStage.index?c.el.prepend(a.personalizedStage.element):c.stageItems.eq(a.personalizedStage.index-1).after(a.personalizedStage.element),a.personalizedStage.isVisible=!0)}function r(a){var c=a.personalizedStage.element.find(g.SELECTORS.stageHeadline);3>a.config.mediaQuery&&(c=a.personalizedStage.element.find(g.SELECTORS.stageHeadline));c.text(a.originalPersonalizedText)}
function F(a,c){n(c.stageContainer,c.slickDots);p(a);setTimeout(function(){var b=c.stageItems.filter(v.NN_SLICK_SELECTORS.currentSlide).find(g.SELECTORS.stageImg).clone();c.el.hasClass(v.NN_SLICK_CLASSES.initialized)&&c.el.slick("unslick");a.windowCountdownInterval&&window.clearInterval(a.windowCountdownInterval);q(a,c);t.default.pub(g.EVENTS.startSlick);c.stageContainer.css("visibility","hidden");c.stageImage.eq(0).before(b);setTimeout(function(){b.addClass(g.CLASSES.stageImgFading)},0);setTimeout(function(){c.stageContainer.css("visibility",
"");b.remove();e(c.stageContainer,c.stageFootnote,c.slickDots,!1,c.stageCountdown)},g.TIME.wait)},g.TIME.wait)}function y(a,c){var b=0;n(c.stageContainer,c.slickDots);setTimeout(function(){var d=c.stageItems.filter(v.NN_SLICK_SELECTORS.currentSlide).find(g.SELECTORS.stageImg).clone();c.el.hasClass(v.NN_SLICK_CLASSES.initialized)&&c.el.slick("unslick");a.windowCountdownInterval&&window.clearInterval(a.windowCountdownInterval);m(a,c);r(a);t.default.pub(g.EVENTS.startSlick);c.stageContainer.css("visibility",
"hidden");0===a.personalizedStage.index&&(b=1);c.stageImage.eq(b).before(d);setTimeout(function(){d.addClass(g.CLASSES.stageImgFading)},0);setTimeout(function(){c.stageContainer.css("visibility","");d.remove();e(c.stageContainer,c.stageFootnote,c.slickDots,!1,c.stageCountdown);a.personalizedStage.element.addClass(G.NN_CLASSES.isHidden)},g.TIME.wait)},g.TIME.wait)}function N(){document.querySelectorAll("video").forEach(function(a){""===a.currentSrc&&a.load()})}Object.defineProperty(d,"__esModule",
{value:!0});d.addFadeInClassesOnLoad=e;d.removeFadeInClassesOnLoad=n;d.addFadeInClassesOnSwipe=function(a,c,b,d,e,f){c.addClass(g.CLASSES.stageContainerFadeIn);a.addClass(g.CLASSES.stageFootnoteFadeIn);f&&f.addClass(g.CLASSES.stageCountdownFadeIn)};d.removeFadeInClassesOnSwipe=function(a,c,b,d,e,f){a.removeClass(g.CLASSES.stageFootnoteFadeIn);c.removeClass(g.CLASSES.stageContainerFadeIn);f&&f.removeClass(g.CLASSES.stageCountdownFadeIn)};d.centerStageImage=function(a,c){var b=$(window).width();b!==
c&&(a.width()>b?a.css("margin-left",-(a.width()-b)/2+"px"):a.css("margin-left",0))};d.initCountdown=function(a){if(a&&a.length)return window.setInterval(function(){a.forEach(k)},1E3)};d.updateCountdownInstance=k;d.updatePersonalizedElementHeader=p;d.removePersonalizedElementFromDOM=m;d.returnPersonalizedElementToInitialPositionInDOM=q;d.restorePersonalizedElementsHeaderText=r;d.addPersonalizedElement=F;d.removePersonalizedElement=y;d.initPersonalizedElement=function(a,c){a.personalizedStage.element.length&&
(A.default.isUserAuthenticated()?(a.personalizedStage.element.removeClass(G.NN_CLASSES.isHidden),p(a)):m(a,c))};d.updatePersonalizedElement=function(a,c){a.personalizedStage.element.length&&(A.default.isUserAuthenticated()&&!a.personalizedStage.isVisible?(a.personalizedStage.element.removeClass(G.NN_CLASSES.isHidden),F(a,c)):a.personalizedStage.isVisible&&y(a,c))};d.getLinkName=function(a,b,d){a.children(c.SELECTORS.stageElemPrice).length?(b=a.find(c.SELECTORS.stageElemModelName).text().trim(),a=
a.find(c.SELECTORS.stageElemPriceHighlightedPrice).text().trim()):(b=b.text().trim(),a=d.text().trim());return b&&a?(0,x.formatToStringTracking)(b)+":"+(0,x.formatToStringTracking)(a):""+(0,x.formatToStringTracking)(b)};d.loadStageMedia=function(c,b){c.each(function(){var c=(b?g.SELECTORS.stageMotionClipDesktop:g.SELECTORS.stageMotionClipMobile)+" \x3e source";(0,a.renameElementAttribute)($(this),B.NN_ATTRIBUTES.lazyloadSrcset,B.NN_ATTRIBUTES.srcset,c);(0,a.renameElementAttribute)($(this),B.NN_ATTRIBUTES.lazyloadSrc,
B.NN_ATTRIBUTES.src,c);N()})};d.enableTrackingOnElement=function(a,c){a.setAttribute(O.NN_TRACKING_DATA_ATTRIBUTES.linkName,c)};d.disableTrackingOnElement=function(a){a.removeAttribute(O.NN_TRACKING_DATA_ATTRIBUTES.linkName)};var g=b("T3o9"),v=b("hgYM"),x=b("53NG"),G=b("K6O9"),B=b("sjBm"),D=b("fDjV"),M=b("lNEE"),A=(f=b("OrK9"))&&f.__esModule?f:{default:f},t=(f=b("2b3J"))&&f.__esModule?f:{default:f},c=b("P7wN"),a=b("bYY5"),O=b("sbRq"),Y=6E4,R=60*Y,w=24*R},"8zbs":function(f,d,b){Object.defineProperty(d,
"__esModule",{value:!0});d.SELECTORS=d.CLASSES=d.MODULE_NAME=void 0;f=b("akNE");b=d.MODULE_NAME="stagepushablecampaign";b=d.CLASSES={stagepushableCampaignBtn:b+"__btn"};d.SELECTORS=(0,f.createSelectorsFromClasses)(b)},"J/dW":function(f,d,b){Object.defineProperty(d,"__esModule",{value:!0});d.NN_WINDOW_NAMES={self:"_self"}},P7wN:function(f,d,b){Object.defineProperty(d,"__esModule",{value:!0});d.SELECTORS=d.CLASSES=d.MODULE_NAME=void 0;f=b("akNE");b=d.MODULE_NAME="stageelementprice";b=d.CLASSES={stageElemPrice:""+
b,stageElemModelName:b+"__modelName",stageElemPriceHighlightedPrice:b+"__highlightedPrice",stageElementForm:b+"__form",textlink:b+"__textlink",stageElemButton:b+"__btn"};d.SELECTORS=(0,f.createSelectorsFromClasses)(b)},T3o9:function(f,d,b){Object.defineProperty(d,"__esModule",{value:!0});d.TIME=d.EVENTS=d.WKO_PARAMETERS=d.PLACEHOLDERS=d.ATTRIBUTES=d.VALUES=d.SLICK_OPTIONS=d.SELECTORS=d.CLASSES=d.EVENTS_NAMESPACE=d.MODULE_NAME=void 0;f=b("akNE");b=b("hgYM");var e=d.MODULE_NAME="stagepushable",n=d.EVENTS_NAMESPACE=
"."+e;e=d.CLASSES={animate:"animate",stageItem:e+"__item",stageItemPersonalized:e+"__item__personalized",stageMotionClipMobile:e+"__motionclip--mobile",stageMotionClipDesktop:e+"__motionclip--desktop",stageImg:e+"__img",stageImgFading:e+"__img--fading",stageLink:e+"__link",stageBtn:e+"__btn",stageWithoutLink:e+"__withoutLink",stageBase:e+"__base",stageContainer:e+"__container",stageContainerFadeIn:e+"__container--fadeIn",stageContainerFadeOut:e+"__container--fadeOut",stageCountdown:e+"__countdown",
stageCountdownFadeIn:e+"__countdown--fadeIn",stageContent:e+"__content",stageFootnote:e+"__footnote",stageFootnoteFadeIn:e+"__footnote--fadeIn",stageHeadline:e+"__hl",stageSubline:e+"__txt",stageAnimateFadeInAndMoveLeft:e+"__animate--fadeInAndMoveLeft",stageSlickDotsFadeIn:e+"__slickDots--fadeIn",stageSlickDotsFadeOut:e+"__slickDots--fadeOut"};d.SELECTORS=(0,f.createSelectorsFromClasses)(e);d.SLICK_OPTIONS=$.extend({},b.NN_SLICK_OPTIONS,{adaptiveHeight:!0,autoplay:!0});d.VALUES={dataLayerPath:["page",
"modules","stage"],imageTag:"img",aemStageLinkClick:"aem_stage_linkclick"};d.ATTRIBUTES={dataSlideDelay:"data-slide-delay",dataCountdownViewListItem:"data-countdown-viewlist-item",slideDelay:"slide-delay",trackingLink:"data-tracking-link"};d.PLACEHOLDERS={firstName:"$firstName",lastName:"$lastName",salutation:"$salutation",title:"$title",namePrefix:"$namePrefix",lastName2:"$lastName2",middleInitial:"$middleInitial",marketSpecificSalutation:"$marketSpecificSalutation",salutationOrTitle:"$salutationOrTitle"};
d.WKO_PARAMETERS={salutation:"salutation",title:"title",namePrefix:"namePrefix",lastName2:"lastName2",middleInitial:"middleInitial",marketSpecificSalutation:"marketSpecificSalutation"};d.EVENTS={startSlick:"slick:start"+n};d.TIME={wait:1E3}},Ygo3:function(f,d){!function(){var b=jQuery,d=1,f=b.fn.animate,k={};b.fn.animate=function(e,m,n,r){var p=b.speed(m,n,r);p.complete=p.old;return this.each(function(){this["jQuery.pause"]||(this["jQuery.pause"]=d++);var r=b.extend({},p);f.apply(b(this),[e,b.extend({},
r)]);k[this["jQuery.pause"]]={run:!0,prop:e,opt:r,start:(new Date).getTime(),done:0}})};b.fn.pause=function(){return this.each(function(){this["jQuery.pause"]||(this["jQuery.pause"]=d++);var e=k[this["jQuery.pause"]];e&&e.run&&(e.done+=(new Date).getTime()-e.start,e.done>e.opt.duration?delete k[this["jQuery.pause"]]:(b(this).stop(),e.run=!1))})};b.fn.resume=function(){return this.each(function(){this["jQuery.pause"]||(this["jQuery.pause"]=d++);var e=k[this["jQuery.pause"]];e&&!e.run&&(e.opt.duration-=
e.done,e.done=0,e.run=!0,e.start=(new Date).getTime(),f.apply(b(this),[e.prop,b.extend({},e.opt)]))})}}()},efd142f2cd:function(f,d,b){f.exports=b("iFIR")},iFIR:function(f,d,b){function e(b){return b&&b.__esModule?b:{default:b}}f=b("e3M3");var n=e(f),k=b("BSTm");f=b("reK4");var p=e(f);f=b("vgUb");var m=e(f),q=function(b){if(b&&b.__esModule)return b;var d={};if(null!=b)for(var e in b)Object.prototype.hasOwnProperty.call(b,e)&&(d[e]=b[e]);d.default=b;return d}(b("T3o9"));window.nn.stagepushable=function(){var b=
{},d={},e=function(){d.currentContext&&d.currentContext.destroy()},f=function(e){d.config.mediaQuery=e;d.currentContext.init(b.el,d.config)},g=function(){d.currentContext=(0,m.default)()},v=function(){d.currentContext=(0,p.default)()};return{init:function(k,m){d.config=$.extend(!0,{},q,m);b.el=k;n.default.start(this,{onInitInMobileContext:g,onInitInDesktopContext:v,onAfterInitContext:f,onChangedToMobileContext:g,onChangedToDesktopContext:v,onBeforeChangedContext:e,onAfterChangedContext:f})},destroy:function(){n.default.stop(this);
d.currentContext&&d.currentContext.destroy();(0,k.nullifyPropertiesOnObject)(b.el)}}}},reK4:function(f,d,b){function e(a,c,b){c in a?Object.defineProperty(a,c,{value:b,enumerable:!0,configurable:!0,writable:!0}):a[c]=b;return a}function n(a){if(Array.isArray(a)){for(var c=0,b=Array(a.length);c<a.length;c++)b[c]=a[c];return b}return Array.from(a)}Object.defineProperty(d,"__esModule",{value:!0});d.default=function(){var a={},b={},d=(0,F.Debouncer)({debounceMs:y.NN_DEBOUNCE_TIME.slow,waitMax:2*y.NN_DEBOUNCE_TIME.slow}),
f=void 0,w=void 0,h=void 0,u=void 0,l=void 0,C=void 0,z=void 0,L=void 0,I=void 0,S=function(){a.stageImage&&b.windowWidth&&((0,k.centerStageImage)(a.stageImage,b.windowWidth),b.windowWidth=$(window).width())},J=function(){var b=a.stageContainer.height();a.stageContainer.eq(0).is(":hidden")&&(b=a.stageContainer.eq(1).height());a.slickDots.css("top",b-a.slickDots.outerHeight(!0)+"px")},K=function(b){a.activeSlickDot=b.find("button");a.activeSlickDot.css("animation-duration",u.autoplaySpeed+"ms").addClass(m.NN_ANIMATION_CLASSES.initSlideProgress)},
E=function(){a.el.find(q.NN_SLICK_SELECTORS.dots).removeClass(w.animate)},T=function(){I&&I.map(function(a){return(0,k.enableTrackingOnElement)(a.element,a.linkname)});I=void 0;(0,k.addFadeInClassesOnSwipe)(a.stageFootnote,a.stageContainer,!1,!1,!1,a.stageCountdown)},U=function(c,d,e,f){I=[].concat(n(d.$slides[e].querySelectorAll("["+t.NN_TRACKING_DATA_ATTRIBUTES.linkName+"]"))).map(function(a){var b=(0,x.safeGet)(a,function(a){return a.getAttribute(t.NN_TRACKING_DATA_ATTRIBUTES.linkName)});b&&(0,
k.disableTrackingOnElement)(a);return{element:a,linkname:b}});c=a.el.find(q.NN_SLICK_SELECTORS.dots).find("li");e=c.eq(e);f=c.eq(f);e[0].id!==f[0].id&&(a.initDelayMs?a.el.slick("slickSetOption","autoplaySpeed",a.initDelayMs):a.el.slick("slickSetOption","autoplaySpeed",u.autoplaySpeed),K(f),e.find("button").css("animation-duration","0s").removeClass(m.NN_ANIMATION_CLASSES.initSlideProgress),b.slideStartTimeStamp=window.Date.now(),(0,k.removeFadeInClassesOnSwipe)(a.stageFootnote,a.stageContainer,!1,
!1,!1,a.stageCountdown),f=e=c=null)},V=function(){a.slickDots=a.el.find(q.NN_SLICK_SELECTORS.dots);a.slickDots=a.slickDots.length?a.slickDots:!1;a.slickDots&&(a.slickDotsButtons=a.slickDots.find("button"),J(),a.slickDots.addClass(w.animate),K(a.slickDots.find("li").eq(u.initialSlide)));var b=a.el[0].querySelector(".stagepushable__motionclip");b&&b.play()},P=function(){a.initDelayMs=a.el.data(l.slideDelay);a.initDelayMs&&(u.autoplaySpeed=parseInt(a.initDelayMs,10));a.el.slick(u);b.isAutoplayOn=!0},
W=function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return document["querySelector"+(a?"All":"")]("ul."+q.NN_SLICK_CLASSES.dots+" "+c.join(" "))},Q=function(){var c=W(!1,"li."+q.NN_SLICK_CLASSES.activeSlide,"button."+m.NN_ANIMATION_CLASSES.initSlideProgress);c&&(c.style.animationDuration="0s",(0,g.removeClass)(c,m.NN_ANIMATION_CLASSES.initSlideProgress));W(!0,"li","button").forEach(function(a){return(0,g.removeClass)(a,m.NN_ANIMATION_CLASSES.pauseProgress)});
a.el.slick("slickPause");b.slideTimeRemainingMs=void 0;a.activeSlickDot.addClass(m.NN_ANIMATION_CLASSES.pauseProgress).removeClass(m.NN_ANIMATION_CLASSES.pauseProgress);a.el.slick("slickPlay")},X=function(){Q();E()},H=function(){Q();E()},Z=function(){a.el.slick("slickPause");var c=window.Date.now()-b.slideStartTimeStamp;var d=a.el.slick("slickGetOption","autoplaySpeed");b.slideTimeRemainingMs=d-c;a.activeSlickDot&&a.activeSlickDot.addClass(m.NN_ANIMATION_CLASSES.pauseProgress);return!0},aa=function(){if(!b.slideStop)return a.activeSlickDot&&
a.activeSlickDot.removeClass(m.NN_ANIMATION_CLASSES.pauseProgress),b.slideTimeRemainingMs&&a.el.slick("slickSetOption","autoplaySpeed",b.slideTimeRemainingMs),a.el.slick("slickPlay"),b.slideStartTimeStamp=window.Date.now(),!0},ba=function(){a.el.on("init",$.proxy(V,this))},ca=function(){a.slickDots&&(a.el.on("beforeChange",$.proxy(U,this)),a.el.on("afterChange",$.proxy(T,this)),a.el.on("click",$.proxy(X,this)),a.el.on("swipe",$.proxy(H,this)),a.el.on("mouseenter",$.proxy(Z,this)),a.el.on("mouseleave",
$.proxy(aa,this)),$(window).on("resize"+z,J));$(window).on("resize"+z,S);r.default.sub(L.startSlick,P);$(window).on("storage",function(c){c.originalEvent.storageArea===sessionStorage&&d.debounce(function(){(0,k.updatePersonalizedElement)(b,a)})})},da=function(){a.el.off("init",$.proxy(V,this));a.slickDots&&(a.el.off("beforeChange",$.proxy(U,this)),a.el.off("afterChange",$.proxy(T,this)),a.el.off("click",$.proxy(X,this)),a.el.off("swipe",$.proxy(H,this)),a.el.off("mouseenter",$.proxy(Z,this)),a.el.off("mouseleave",
$.proxy(aa,this)));$(window).off(z);r.default.unsub(L.startSlick,P);d.kill()},ea=function(){ba();P();S();(0,G.isImageLoaded)(a.stageImageTag.first()[0],function(){(0,k.addFadeInClassesOnLoad)(a.stageContainer,a.stageFootnote,a.slickDots,!1,a.stageCountdown)});ca()},fa=function(){var c=(0,g.isElementInViewport)(a.el);c&&!b.isAutoplayOn?(aa(),b.isAutoplayOn=!0):!c&&b.isAutoplayOn&&(Z(),b.isAutoplayOn=!1);return!0},ha=function(){for(var a=$(h.stageItem),c=0;c<a.length;c++)!function(c){c=a.eq(c);var b=
c.find(h.stageWithoutLink),d=b.length?"":c.find("["+l.trackingLink+"]"),g=c.find(h.stageHeadline),X=c.find(h.stageSubline),H=c.find(D.SELECTORS.stagepushableCampaignBtn),m=c.find(B.SELECTORS.stageElementForm),n=g.length?(0,k.getLinkName)(c,g,X):"";b.length&&!b.attr("href")&&b.replaceWith('\n                        \x3cdiv class\x3d"'+w.stageWithoutLink+'"\x3e\n                            '+b.html()+"\n                        \x3c/div\x3e\n                    ");if(m.length){var p;r.default.pub(A.NN_EVENTS_MODULE_LIFECYCLE.afterInit,
{$el:c,additionalTracking:[{$elements:"button",trackingData:(p={},e(p,t.NN_TRACKING_DATA_ATTRIBUTES.linkName,n),e(p,t.NN_TRACKING_DATA_ATTRIBUTES.linkPosition,f),e(p,t.NN_TRACKING_DATA_ATTRIBUTES.linkDestination,m.attr("action")),p)}]})}H.length&&r.default.pub(A.NN_EVENTS_MODULE_LIFECYCLE.afterInit,{$el:c,additionalTracking:H.toArray().map(function(a,c){var b;c=H.eq(c).text().trim();return{$elements:$(a),trackingData:(b={},e(b,t.NN_TRACKING_DATA_ATTRIBUTES.linkName,n+":"+(0,M.formatToStringTracking)(c)),
e(b,t.NN_TRACKING_DATA_ATTRIBUTES.linkPosition,f),b)}})});if(d.length&&!H.length){var q;r.default.pub(A.NN_EVENTS_MODULE_LIFECYCLE.afterInit,{$el:c,additionalTracking:[{$elements:"a",trackingData:(q={},e(q,t.NN_TRACKING_DATA_ATTRIBUTES.linkName,n),e(q,t.NN_TRACKING_DATA_ATTRIBUTES.linkPosition,f),q)}]})}}(c);a=null},ia=function(){b.watcher=v.default.start(a.el[0],fa)};return{init:function(d,e){a.el=d;b.config=e;f=e.MODULE_NAME;w=e.CLASSES;h=e.SELECTORS;u=e.SLICK_OPTIONS;l=e.ATTRIBUTES;C=e.VALUES;
z=e.EVENTS_NAMESPACE;L=e.EVENTS;b.windowWidth=0;ha();a.stageItems=a.el.find(h.stageItem);a.stageImage=a.el.find(h.stageImg);a.stageImageTag=a.stageImage.find(C.imageTag);a.stageContainer=a.el.find(h.stageContainer);a.stageFootnote=a.el.find(h.stageFootnote);a.stageCountdown=a.el.find(h.stageCountdown);a.stageCountdown=a.stageCountdown[0]?a.stageCountdown:!1;a.stageWithoutLink=a.el.find(h.stageWithoutLink);b.personalizedStage={element:a.el.find(h.stageItemPersonalized),originalPersonalizedText:"",
index:0,isVisible:!0};(0,k.initPersonalizedElement)(b,a);ea();a.stageCountdown&&(b.windowCountdownInterval=(0,k.initCountdown)(a.stageCountdown.toArray()));a.slickDots&&(0,N.runAfterLoad)(ia);(0,c.loadStageMedia)(a.stageImage,!1)},destroy:function(){v.default.destroy(b.watcher);a.stageWithoutLink.length&&a.stageWithoutLink.replaceWith('\x3ca class\x3d"stagepushable__withoutLink"\x3e'+a.stageWithoutLink.html()+"\x3c/a\x3e");a.el.hasClass(q.NN_SLICK_CLASSES.initialized)&&a.el.slick("unslick");b.windowCountdownInterval&&
window.clearInterval(b.windowCountdownInterval);(0,k.removeFadeInClassesOnSwipe)(a.stageFootnote,a.stageContainer);(0,k.returnPersonalizedElementToInitialPositionInDOM)(b,a);(0,k.restorePersonalizedElementsHeaderText)(b);a.stageImage.css("margin-left",0);da();(0,p.nullifyPropertiesOnObject)(a)}}};b("Ygo3");var k=b("2sPK"),p=b("BSTm"),m=b("BWLg"),q=b("hgYM"),r=(f=b("2b3J"))&&f.__esModule?f:{default:f},F=b("zF+s"),y=b("BcMv"),N=b("viDy"),g=b("bYY5"),v=(f=b("tU8a"))&&f.__esModule?f:{default:f},x=b("rMq/"),
G=b("BCBw"),B=b("P7wN"),D=b("8zbs"),M=b("53NG"),A=b("+ly4"),t=b("sbRq"),c=b("2sPK")},vgUb:function(f,d,b){function e(c){return c&&c.__esModule?c:{default:c}}Object.defineProperty(d,"__esModule",{value:!0});d.default=function(){var c={},a={slideLink:null},b=(0,N.Debouncer)({debounceMs:g.NN_DEBOUNCE_TIME.slow,waitMax:2*g.NN_DEBOUNCE_TIME.slow}),d=void 0,e=void 0,f=void 0,h=void 0,u=void 0,l=void 0,C=void 0,z=void 0,L=function(c,b){a.slideLink=b.$slides.eq(2<arguments.length&&void 0!==arguments[2]?arguments[2]:
0).find(f.stageLink).attr("href")},I=function(a,b,d,f){d!==f&&((a=c.el.data(e.slideDelay))?c.el.slick("slickSetOption","autoplaySpeed",a):c.el.slick("slickSetOption","autoplaySpeed",u.autoplaySpeed))},S=function(){var b=!1;c.stageImage.on("mousedown"+l+" touchstart"+l+" pointerdown"+l,function(){b=!1}).on("mousemove"+l+" touchmove"+l+" pointermove"+l,function(){b=!0}).on("mouseup"+l+" touchend"+l+" pointerup"+l,function(c){var d=b,e=$(c.target).attr("href");b=!1;c.preventDefault();d||(a.slideLink?
window.open(a.slideLink,q.NN_WINDOW_NAMES.self):e&&window.open(e,q.NN_WINDOW_NAMES.self))});c.el.on("mouseup"+l+" touchend"+l+" pointerup"+l,m.NN_SLICK_SELECTORS.dots,function(a){a.stopPropagation()})},J=function(){var b=c.el.data(e.slideDelay);b&&(u.autoplaySpeed=parseInt(b,10));(0,B.isRtl)()&&(c.el.attr("dir","rtl"),u.rtl=!0);c.el.slick(u);c.slickDots=c.el.find(m.NN_SLICK_SELECTORS.dots);c.slickDots=c.slickDots.length?c.slickDots:!1;F.default.start(a.instance,{$slickInstance:c.el,slickOptions:u});
c.stageItems.show();c.el.slick("setPosition");if(b=c.el.slick("slickCurrentSlide"))a.slideLink=c.el.slick("getSlick").$slides.eq(b).find(f.stageLink).attr("href");a.isAutoplayOn=!0},K=function(){c.el.slick("slickPause");var b=window.Date.now()-a.slideStartTimeStamp;var d=c.el.slick("slickGetOption","autoplaySpeed");a.slideTimeRemainingMs=d-b;return!0},E=function(){a.slideTimeRemainingMs&&c.el.slick("slickSetOption","autoplaySpeed",a.slideTimeRemainingMs);c.el.slick("slickPlay");a.slideStartTimeStamp=
window.Date.now();return!0},T=function(){var b=(0,r.isElementInViewport)(c.el);b&&!a.isAutoplayOn?(E(),a.isAutoplayOn=!0):!b&&a.isAutoplayOn&&(K(),a.isAutoplayOn=!1);return!0},U=function(){c.stageItems=c.el.find(f.stageItem);c.stageImage=c.el.find(f.stageImg);c.stageImageTag=c.stageImage.find(C.imageTag);c.stageContainer=c.el.find(f.stageContainer);c.stageFootnote=c.el.find(f.stageFootnote);c.stageBase=c.el.closest(f.stageBase);c.stageHeadline=c.el.find(f.stageHeadline);c.stageSubline=c.el.find(f.stageSubline);
c.stageLink=c.el.find(f.stageLink);c.stageCountdown=c.el.find(f.stageCountdown);c.stageCountdown=c.stageCountdown[0]?c.stageCountdown:!1;c.stageWithoutLink=c.el.find(f.stageWithoutLink);c.stageForm=c.stageItems.find(k.SELECTORS.stageElementForm);c.el.find(f.stageBtn).each(function(){var a=$(this),b=a.closest(f.stageLink);a.replaceWith(function(){return'\x3ca class\x3d"'+h.stageBtn+" "+G.NN_CLASSES.isMobile+'" href\x3d"'+b.attr("href")+'" data-tracking-link\x3e'+this.innerHTML+"\x3c/a\x3e"})});c.stageButton=
c.stageItems.find("["+e.trackingLink+"]");c.stageChildren=c.stageLink.children();c.stageChildren.unwrap();a.personalizedStage={element:c.el.find(f.stageItemPersonalized),originalPersonalizedText:"",index:0,isVisible:!0}},V=function(){if(c.slickDots)c.el.on("beforeChange"+l,I).on("afterChange"+l,L).on("mouseenter",$.proxy(K,this)).on("click",$.proxy(E,this)).on("mouseleave",$.proxy(E,this));c.stageButton.on("click"+l,Q);c.stageForm.on("submit"+l,Q);y.default.sub(z.startSlick,J);$(window).on("storage",
function(d){d.originalEvent.storageArea===sessionStorage&&b.debounce(function(){(0,n.updatePersonalizedElement)(a,c)})})},P=function(){c.stageButton.off(l);c.stageForm.off(l);c.el.off(l);c.el.off("mouseenter",$.proxy(K,this));c.el.off("mouseleave",$.proxy(E,this));$(window).off(l);y.default.unsub(z.startSlick,J);b.kill()},W=function(){a.watcher=v.default.start(c.el[0],T)},Q=function(){var a=$(this),b=a.parents(f.stageItem),c=b.find(f.stageHeadline),e=b.find(f.stageSubline),g=b.find(k.SELECTORS.stageElementForm),
h=b.find(f.stageWithoutLink);h.length&&!h.attr("href")?h.replaceWith('\x3cdiv class\x3d"stagepushable__withoutLink"\x3e'+h.html()+"\x3c/div\x3e"):(c=(0,t.getLinkName)(b,c,e),e=a.attr("href"),b.find(k.SELECTORS.stageElementForm).length?e=g.attr("action"):b.find(A.SELECTORS.stagepushableCampaignBtn).length&&(c=c+":"+(0,D.formatToStringTracking)(a.text().trim())),y.default.pub(M.NN_TRACKING_DATA_EVENTS.modifyDataLayerObjectOnUserInteraction,{dataLayerPath:C.dataLayerPath,data:{linkName:c,linkPosition:d,
linkdestinationurl:e},isDataPushedToArray:!0}),_satellite.track(C.aemStageLinkClick))};return{init:function(b,g){d=g.MODULE_NAME;e=g.ATTRIBUTES;f=g.SELECTORS;h=g.CLASSES;u=g.SLICK_OPTIONS;l=g.EVENTS_NAMESPACE;C=g.VALUES;z=g.EVENTS;c.el=b;a.config=$.extend({},g);a.moveStageContainerLeft=!0;a.instance=this;U();(0,n.initPersonalizedElement)(a,c);J();V();S();c.stageCountdown&&(a.windowCountdownInterval=(0,n.initCountdown)(c.stageCountdown.toArray()));c.slickDots&&(0,x.runAfterLoad)(W);(0,t.loadStageMedia)(c.stageImage,
!0)},destroy:function(){c.stageItems.each(function(a,b){a=$("\x3ca\x3e",{class:h.stageLink,href:c.stageLink[a]?c.stageLink[a].attributes.href.value:"#"});$(b).wrapInner(a)});v.default.destroy(a.watcher);c.stageWithoutLink.length&&c.stageWithoutLink.replaceWith('\x3ca class\x3d"stagepushable__withoutLink"\x3e'+c.stageWithoutLink.html()+"\x3c/a\x3e");c.el.find(f.stageItem).length&&(P(),F.default.stop(this),c.el.slick("unslick"));a.windowCountdownInterval&&window.clearInterval(a.windowCountdownInterval);
(0,n.returnPersonalizedElementToInitialPositionInDOM)(a,c);(0,n.restorePersonalizedElementsHeaderText)(a);(0,p.nullifyPropertiesOnObject)(c)}}};var n=b("2sPK"),k=b("P7wN"),p=b("BSTm"),m=b("hgYM"),q=b("J/dW"),r=b("bYY5");f=b("1zF+");var F=e(f);f=b("2b3J");var y=e(f),N=b("zF+s"),g=b("BcMv");f=b("tU8a");var v=e(f),x=b("viDy"),G=b("K6O9"),B=b("M9gL"),D=b("53NG"),M=b("sbRq"),A=b("8zbs"),t=b("2sPK")}},["efd142f2cd"]);