webpackJsonp(["teaserbox/publish/teaserbox/target"],{"24W3":function(d,c,a){function e(a){return a&&a.__esModule?a:{default:a}}d=a("e3M3");var m=e(d),h=a("BSTm");d=a("2b3J");var r=e(d),g=a("+ly4");d=a("QTFI");var k=e(d);d=a("Dt7t");var n=e(d),l=a("lW7b"),v=function(a){if(a&&a.__esModule)return a;var c={};if(null!=a)for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&(c[d]=a[d]);c.default=a;return c}(l);window.nn[l.MODULE_NAME]=function(){var a={},c={},d=void 0,b=void 0,e=function(){var a=!1;
$(document).on("mousedown"+b+" touchstart"+b+" pointerdown"+b,d.teaserElementLink,function(){a=!1}).on("mousemove"+b+" touchmove"+b+" pointermove"+b,d.teaserElementLink,function(){a=!0}).on("mouseup"+b+" touchend"+b+" pointerup"+b,d.teaserElementLink,function(b){var c=a;a=!1;c&&b.preventDefault()})},A=function(){a.currentContext&&a.currentContext.destroy()},f=function(){a.currentContext.init(c.el,a.config)},t=function(){a.currentContext=(0,n.default)()},u=function(){a.currentContext=(0,k.default)()};
return{init:function(w,p){c.el=w;a.config=$.extend(!0,{},v,p);p=a.config;d=p.SELECTORS;b=p.EVENTS_NAMESPACE;e();m.default.start(this,{onInitInMobileContext:t,onChangedToMobileContext:t,onInitInDesktopContext:u,onChangedToDesktopContext:u,onBeforeChangedContext:A,onAfterInitContext:f,onAfterChangedContext:f});p=0<c.el.closest(d.teaserboxOnhomeBU).length?l.MODULE_HOMEBU:null;r.default.pub(g.NN_EVENTS_MODULE_LIFECYCLE.afterInit,{$el:w,moduleName:l.MODULE_NAME,wrapperModuleName:p})},destroy:function(){$(document).off(b);
m.default.stop(this);(0,h.nullifyPropertiesOnObject)(c)}}}},"78e5d9b40a":function(d,c,a){d.exports=a("24W3")},C8lJ:function(d,c,a){Object.defineProperty(c,"__esModule",{value:!0});c.doActionWhenEnterinIframe=function(a,c,d){var e=!1,g=$(c),k=$(window),m=function(){!0===e&&a(g)},l=function(){e=!1},h=function(){e=!1},q=function(){e=!0};k.focus();g.on("mouseenter",q);g.on("mouseleave",h);k.on("blur",m);k.on("focus",l);d&&d.then(function(){g.off("mouseenter",q);g.off("mouseleave",h);k.off("blur",m);k.off("focus",
l);k=g=null})}},Dt7t:function(d,c,a){function e(a){return a&&a.__esModule?a:{default:a}}Object.defineProperty(c,"__esModule",{value:!0});c.default=function(){var a=void 0,c=void 0,b=void 0,d=void 0,e={},f={},t=function(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:0;f.mainTeaserTopic.html(f.mobileTeasers.find(a.teaserTopic).eq(b).html())},u=function(){f.mobileList.each(function(){$(this).hasClass(k.NN_SLICK_CLASSES.initialized)&&($(this).slick("unslick"),h.default.stop(e.self,{$slickElement:$(this)}));
$(this).off(b)})},x=function(){$(f.mobileList).each(function(){1<$(this).find(a.teaserElement).length&&($(this).slick(d),h.default.start(e.self,{$slickElement:$(this)}),$(this).on("beforeChange"+b,function(){var b=$(this);b.length&&(b=b.find(k.NN_SLICK_SELECTORS.activeSlide),(b=b.find(a.videoJS)[0])&&b.player&&b.player.pause())}),$(this).on("afterChange"+b,function(a,b,c){t(c);v.default.pub(l.NN_DOM_EVENTS.dynamicContentChange,{contentHolder:f.mobileTeasers.eq(c)})}))})};return{init:function(g,h){f.el=
g;e.self=this;c=h.CLASSES;a=h.SELECTORS;b=h.EVENTS_NAMESPACE;d=h.SLICK_OPTIONS;f.mobileList=f.el.find(m.NN_SELECTORS.isMobile+" "+a.columnList);f.mobileTeasers=f.mobileList.find(a.teaserElement);f.mainTeaserTopic=f.el.find(a.mainTeaserTopic);f.mobileTeaserList=f.el.find(a.teaserList);f.topics=f.mobileTeasers.find(a.teaserTopic);r.default.start(this,{$slickInstance:f.mobileList,slickOptions:d});1===f.topics.length&&(f.topics.addClass(n.NN_CLASSES.isHidden),f.mainTeaserTopic.removeClass(n.NN_CLASSES.isHidden),
e.topicIndexToRemoveOnDestroy=q.default.cloneTopicName(f.mobileTeasers),t());x();f.mobileList.find(a.teaserElementIsText).length&&f.mobileTeaserList.addClass(c.teaserListIsText);f.el.find(k.NN_SLICK_SELECTORS.dots).css("bottom","")},destroy:function(){q.default.removeCopiedTopics(f.mobileTeasers,e.topicIndexToRemoveOnDestroy);f.mainTeaserTopic.addClass(n.NN_CLASSES.isHidden);f.topics.removeClass(n.NN_CLASSES.isHidden);f.mainTeaserTopic.empty();u();r.default.stop(this);(0,g.nullifyPropertiesOnObject)(f)}}};
var m=a("bdJJ");d=a("4lJa");var h=e(d);d=a("1zF+");var r=e(d),g=a("BSTm"),k=a("hgYM"),n=a("K6O9"),l=a("+ly4");d=a("2b3J");var v=e(d);a=a("kGSz");var q=e(a)},QTFI:function(d,c,a){Object.defineProperty(c,"__esModule",{value:!0});c.default=function(){var a={},b={},c=void 0,d=void 0,f=void 0,t=function(){1===b.topics.length&&b.visibleTeasers.each(function(){$(this).find(c.teaserTopic).length||$(this).hasClass(d.teaserElementIsText)||$(this).addClass(d.teaserElementOneTopic)})},u=function(a){$(a).each(function(){var a=
$(this).find(c.teaserElement),b=a.length;1<b&&(b=Math.floor(Math.random()*(b-1-0+1))+0,a.hide().eq(b).show())})},x=function(){a.iFrameClickPromise=new q.default(function(b){a.iFrameClickPromiseResolveCallback=b})},p=function(){var a=b.el.find(c.teaserElementVideo);b.visibleVideoElements=a.filter(function(a,b){return(0,e.isElementVisible)(b)});b.desktopColumns=b.el.find(g.NN_SELECTORS.isDesktop).find(c.column);b.desktopTeasers=b.desktopColumns.find(c.teaserElement);b.teaserElementText=b.el.find(c.teaserElementIsText);
b.teaserList=b.el.find(c.teaserList);b.columns=b.el.find(c.column);b.visibleTeasers=b.desktopTeasers.filter(":visible");b.topics=b.visibleTeasers.find(c.teaserTopic);a=null},y=function(a){a.hasClass(r.NN_CLASSES.isAmplifyingOnMouseOver)&&a.removeClass(r.NN_CLASSES.isAmplifyingOnMouseOver)},B=function(){y($(this))},C=function(a){y(a.closest(g.NN_SELECTORS.isAmplifyingOnMouseOver))},z=function(){a.youtubeInstancesWhereCreated||(a.youtubeInstancesWhereCreated=!0,b.visibleVideoElements.each(function(b,
c){b=$(c).find("iframe");b.length&&(0,v.doActionWhenEnterinIframe)(C,b,a.iFrameClickPromise)}))},D=function(){a.incrementerColumnAnimation=1;b.columns.addClass(l.NN_ANIMATION_CLASSES.componentStateAnimateFrom).each(function(){w.default.start(this,function(b){$(b.element).removeClass(l.NN_ANIMATION_CLASSES.componentStateAnimateFrom).css("transition-delay",a.incrementerColumnAnimation*k.NN_TIME.fast+"ms").addClass(l.NN_ANIMATION_CLASSES.componentStateAnimateTo);a.incrementerColumnAnimation++},{threshold:.25})})};
return{init:function(e,g){b.el=e;d=g.CLASSES;c=g.SELECTORS;f=g.EVENTS_NAMESPACE;x();p();b.visibleVideoElements.on("click"+f,B);$(document).on(n.NN_DOM_EVENTS.initModuleHasFinishedInitialising,z);a.youtubeInstancesWhereCreated=!1;b.teaserList.toggleClass(d.teaserListIsText,b.teaserElementText.length);u(b.desktopColumns);t();(0,h.runAfterLoad)(D)},destroy:function(){b.teaserList.removeClass(d.teaserListIsText);b.visibleTeasers.removeClass(d.teaserElementOneTopic);b.visibleVideoElements.off(f);$(document).off(n.NN_DOM_EVENTS.initModuleHasFinishedInitialising,
z);a.iFrameClickPromiseResolveCallback();(0,m.nullifyPropertiesOnObject)(b)}}};var e=a("bYY5"),m=a("BSTm"),h=a("viDy"),r=a("K6O9"),g=a("bdJJ"),k=a("BcMv"),n=a("+ly4"),l=a("BWLg"),v=a("C8lJ"),q=(d=a("A/Xc"))&&d.__esModule?d:{default:d},w=(a=a("tU8a"))&&a.__esModule?a:{default:a}},kGSz:function(d,c,a){Object.defineProperty(c,"__esModule",{value:!0});var e=a("lW7b");c.default={cloneTopicName:function(a){var c=[];a.find(e.SELECTORS.teaserTopic).length&&a.each(function(d){$(this).find(e.SELECTORS.teaserTopic).length||
($(this).prepend(a.find(e.SELECTORS.teaserTopic).eq(d-1).clone()),c.push(d))});return c},removeCopiedTopics:function(a,c){$(c).each(function(c,d){a.find(e.SELECTORS.teaserTopic).eq(d).remove()})}}},lW7b:function(d,c,a){Object.defineProperty(c,"__esModule",{value:!0});c.ATTRIBUTES=c.SELECTORS=c.SLICK_OPTIONS=c.CLASSES=c.EVENTS_NAMESPACE=c.MODULE_HOMEBU=c.MODULE_NAME=void 0;d=a("akNE");a=a("hgYM");var e=c.MODULE_NAME="teaserbox";c.MODULE_HOMEBU="homebuteaser";c.EVENTS_NAMESPACE="."+e;e=c.CLASSES={column:e+
"__column",columnList:"teaserElement__list",teaserElement:"teaserElement__item",teaserElementVideo:"teaserElement__video",teaserElementOneTopic:"teaserElement__item-one-topic",teaserElementIsText:"teaserElement__item--is-text",teaserElementLink:"teaserElement__link",teaserList:e+"__list",teaserListIsText:e+"__list--is-text",teaserTopic:"teaserElement__hl--topic",mainTeaserTopic:"teaserElement__hl--mainTopic",subHl:"teaserElement__hl--sub",videoJS:"video-js",teaserboxOnhomeBU:"teaserboxonhome__base"};
c.SLICK_OPTIONS=$.extend({},a.NN_SLICK_OPTIONS,{arrows:!1,autoplaySpeed:4E3});c.SELECTORS=(0,d.createSelectorsFromClasses)(e);c.ATTRIBUTES={slickBulletsMarginBottom:15}}},["78e5d9b40a"]);